# Generated by Django 5.2.12 on 2026-04-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, verbose_name='Режисер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Жанри текстом'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_static',
            field=models.CharField(blank=True, max_length=255, verbose_name='Постер у static'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік'),
        ),
        migrations.AddField(
            model_name='movie',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Джерело'),
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.TextField(blank=True, verbose_name='У головних ролях'),
        ),
        migrations.AddField(
            model_name='session',
            name='format_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Формат'),
        ),
    ]
